[20160803-130724]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/ConsultarLogo.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20160803-130724]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20160803-130724]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20160803-130724]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20160803-130724]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20160803-130724]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20160803-130724]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20160803-130724]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20160803-130724]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20160803-130724]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20160803-130724]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20160803-130724]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20160803-130724]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20160803-130724]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20160803-130724]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20160803-130724]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20160803-130724]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20160803-130724]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20160803-130724]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20160803-130724]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20160803-130724]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20160803-130724]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20160803-130724]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20160803-130724]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20160803-130724]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20160803-130724]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20160803-130724]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20160803-130724]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20160803-130724]: 	at java.lang.Thread.run(Thread.java:662)
[20160803-130724]: Caused by: java.lang.NullPointerException
[20160803-130724]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.ConsultarLogoAction.executeAction(ConsultarLogoAction.java:31)
[20160803-130724]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.AdministracaoBaseAction.execute(AdministracaoBaseAction.java:36)
[20160803-130724]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20160803-130724]: 	... 26 more
[20160803-130724]: .
